# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 3) do

  create_table "authors", :force => true do |t|
    t.column "name", :string
    t.column "ip", :string
  end

  create_table "backlinks", :id => false, :force => true do |t|
    t.column "page_id", :integer, :default => 0, :null => false
    t.column "connected_page_id", :integer, :default => 0, :null => false
  end

  create_table "pages", :force => true do |t|
    t.column "title", :string, :default => "", :null => false
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "revisions", :force => true do |t|
    t.column "page_id", :integer
    t.column "author_id", :integer
    t.column "created_at", :datetime
    t.column "body", :text
  end

end
