development:
  adapter: mysql
  database: qb_branch_development
  host: localhost
  username: rff
  password:

test:
  adapter: mysql
  database: qb_branch_test
  host: localhost
  username: rff
  password:

production:
  adapter: mysql
  database: qb_branch_development
  host: localhost
  username: rff
  password:
